### PR TITLE
Changed  display function for better async handling and error management

### LINKED ISSUE #126: Optimize Profile Display Code for Improved Performance and Error Handling
I was going through the **profile.js**  file and noticed many ways that we can optimize this code. I would like suggestions to refactor and improve the following code  -: 

**Improvement to be made** 

1. Enhance error handling and ensure the connection is released properly.
2. Replace MySQL's callback pattern with async/await for cleaner code.
3. Ensure token validation is handled securely and efficiently.
4. Simplify and organize the structure of the response object.

### PR DESCRIPTION
**Pull request by RishiVT2004**
Fixes #126 
**Changes Implemented**

- Implemented promise-based query execution using `util.promisify` to improve async handling.
- Enhanced error handling with proper logging and appropriate HTTP status codes (401 for unauthorized, 404 for not found, 500 for server errors).
- Added a check for empty results to return 404 when the user is not found in the database.
- Structured the API response to include user details inside a `user` object for better clarity.
- Ensured connection release in the `finally` block to prevent connection leaks.

### CODE REVIEW

**Comment by RishiVT2004** [comment]
@Harshdev098 i am getting PR Description Check / validate-pr-description (pull_request) as unsuccessful , may i know why ?

**Comment by Harshdev098** [comment]
Will add new workflow, its like not working properly

**Review by Harshdev098 — COMMENTED** [review]
Its giving error while displaying data

image

**Comment by RishiVT2004** [comment]
@Harshdev098 there is some issue , I am unable to push my pr , I will delete the current branch and then push with a new branch 
You can close this pr I will send the next one by tonight

**Pull request closed without merging**
