### PR TITLE
Fix :Form Submission Triggering on Empty Required Fields 

### LINKED ISSUE #16: Form Submission Triggering on Empty Required Fields
**Describe the bug**
The problem in the pages (like login,signup,contact us, etc.. ) is the form submission. If the required field is empty then also it sends a request to the server, which should not be the case 

**Expected behavior**
Whenever the user has left a required field. It should not trigger the event for sending any request to the server and just give an alert message to the user about the required fields

### PR DESCRIPTION
**Pull request by ADeshmukh80**
Fixes #16

The solution adds manual validation to the login process by checking if both the email and password fields are filled before sending a request to the server. If either field is empty, it shows an alert message and prevents the submission, ensuring that the user provides the required information before proceeding.

### CODE REVIEW

**Review by Harshdev098 — COMMENTED** [review]
Its all set, but please follow guidelines listed in  [Contributing.md](https://github.com/Harshdev098/Research-Nexas/blob/main/Contributing.md)
Add issue number in description of pr `Fixes#<issue_number>` if you are referencing this pr with an issue 
also edit the title with `Fix:<your title>`

**Comment by ADeshmukh80** [comment]
Sure ...!!!

**Comment by ADeshmukh80** [comment]
Thank you for suggesting 
Looking for merging request!!

**Comment by Harshdev098** [comment]
Thanks for your contribution @ADeshmukh80 . If you would like to contribute more just create an issue and start contributing or work on an existing issue

**Comment by ADeshmukh80** [comment]
Yes...Sure!!!

**Pull request merged**
