### PR TITLE
fixing e contributors page ✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
the contributors page has been fixed.
#203 solved.
@Harshdev098 can you review this PR.

https://github.com/user-attachments/assets/b7538159-4bab-4afd-a2a0-a411200fca1b

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [X] I have followed all the guidlines mentioned in CONTRIBUTING.md.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation (if applicable).
- [X] I have tested it locally and it works fine.
- [X] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [X] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

### CODE REVIEW

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
Don't make another folder for contributors edit the gitContributors.html file and its styling in the style folder, also add the contibuto.js file in the script file

**Comment by T-Rahul-prabhu-38** [comment]
@Harshdev098 it can be done , but i feel this structure is more organised and the code is well spread out. this makes it easier to debug aswell.

however i can fix the changes u asked , should i do that?

**Comment by Harshdev098** [comment]
@T-Rahul-prabhu-38 Yaa, do it please!

**Comment by T-Rahul-prabhu-38** [comment]
sure

**Comment by T-Rahul-prabhu-38** [comment]
@Harshdev098 i have added them to the required folders

**Comment by T-Rahul-prabhu-38** [comment]
@Harshdev098 please review this.

**Comment by Harshdev098** [comment]
fix this, you have not changed the link

image

**Comment by T-Rahul-prabhu-38** [comment]
@Harshdev098 sure ill fix this , im so sorry for the delay , i have my internals going on. ill try fixing at the earliest.

**Comment by T-Rahul-prabhu-38** [comment]
@Harshdev098 yup it should be fixed.

**Pull request merged**
