### PR TITLE
Enhance JWT Token Management

### PR DESCRIPTION
**Pull request by RishiVT2004**
Fixed Issue #99 

**Changes Made to the codebase**

**1. Added Middleware for Environment Variable Validation**

Introduced a checkKey middleware function to validate the presence of ACCESS_TOKEN_SECRET in environment variables 
and assign it to req.Key for use in subsequent functions.

**2. Refactored generateAccessToken Function**

Improved error handling with specific messages for token generation failure and server errors.
Returned the token as a JSON object with a clear key.

**3. Improved decodeAccessToken Function**

Streamlined error checking for the authorization header.
Removed redundant checks and ensured the function handles decoding the token appropriately.
Returned error messages with appropriate status codes for missing authorization headers, token decoding failures, and invalid or expired tokens.

**4. Consistent Error Responses**

Ensured that all error responses are formatted consistently with proper status codes and messages.

### CODE REVIEW

**Comment by RishiVT2004** [comment]
@Harshdev098 please review this pr and add necessary tags(hacktoberfest and gssoc)

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
Its giving error, I think its because you have changed the parameters of the `generateAccessToken` and `decodeAccessToken` , and its very overwhelming to update these functions in every files, if there is any other method to add the middleware you can go with it, or discard the changes done for setting the middleware `checkKey` because i think its not that necessary

**Comment by Harshdev098** [comment]
OR you can update the functions in the files

**Comment by RishiVT2004** [comment]
@Harshdev098 i think refactoring the code will cause too much issue in the future , let me try to simplify and change the code according to its needs

**Comment by Harshdev098** [comment]
Yah, right

**Comment by RishiVT2004** [comment]
@Harshdev098 check if this is good enough or not and let me know

**Pull request merged**
