### PR TITLE
Enhancing and improving the "why join us?" section with proper styling and alignment.

### LINKED ISSUE #350: Enhancing and improving the "why join us?" section with proper styling and alignment.
Enhancing and improving the "why join us?" section with proper styling and alignment.
Screenshot 2024-10-31 090614

### PR DESCRIPTION
**Pull request by shriyadindi**
## 📋 Description

Enhancing and improving the "why join us?" section with proper styling and alignment.

issue no.: #350 
BEFORE: 
Screenshot 2024-10-31 090614

AFTER: 

https://github.com/user-attachments/assets/3f9b4f0a-5ba1-4647-8d88-534c9e4d03f0

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] I have followed all the guidlines mentioned in CONTRIBUTING.md.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

- Fixes #350 

*Thank you for contributing to Research Nexus! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by Harshdev098** [comment]
@shriyadindi It seems the previous PR changes are included in this PR, open a PRs with different branches and make sure your previous changes of the PR does not included

**Comment by shriyadindi** [comment]
@Harshdev098 Okay

**Comment by shriyadindi** [comment]
@Harshdev098 I've opened a new branch and created a New PR for it.
https://github.com/Harshdev098/Research-Nexas/pull/363

**Comment by shriyadindi** [comment]
@Harshdev098 Kindly assign the labels

**Pull request merged**
