### PR TITLE
Enhance the top-researchers section

### LINKED ISSUE #259: Enhance the top-researchers section
The top-researchers sesction is not look so attractive.

I would like to enhance its design and also add hover-effect.

Screenshot 2024-10-21 004116

### PR DESCRIPTION
**Pull request by Sudhanshu248**
## 📋 Description

The top-researchers sesction is not look so attractive.

I've enhanced the design and added hover effect which make it more attractive.

## 🔨 Changes Made

Issue: Enhance the top-researchers section #259
Issue no: #259 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x ] I have followed all the guidlines mentioned in CONTRIBUTING.md.
- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have tested it locally and it works fine.
- [ x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] New feature (non-breaking change which adds functionality) ✨

- Fixes #259 

## 📸 Screenshots (if applicable)

Before:

Screenshot 2024-10-21 004116

After:

https://github.com/user-attachments/assets/836e1b3a-cdd6-4f25-8a1d-5c3afd728546

*Thank you for contributing to Research Nexus! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by Sudhanshu248** [comment]
@Harshdev098 Please review my pr and also add the label of gssoc'24, gssoc-ext, hacktoberfest'24, hacktoberfest-accepted, level-2/3.

**Comment by Sudhanshu248** [comment]
@Harshdev098 Please review my pr and also add the label of gssoc'24, gssoc-ext, hacktoberfest'24, hacktoberfest-accepted, level-2/3.

**Comment by Harshdev098** [comment]
There are conflicts in this branch, resolves them!

**Comment by Sudhanshu248** [comment]
@Harshdev098 Sir, I've solved the conflict.

Please review my pr and also add the label of gssoc'24, gssoc-ext, hacktoberfest'24, hacktoberfest-accepted, level-2/3.

**Pull request merged**
