### PR TITLE
✨chatbot has been added ✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
issue #151 solved.

- the chatbot has been added and its trained on these html files and can answer user queries.
@Harshdev098 can you review this , thank you.

https://github.com/user-attachments/assets/ce1c05fe-a7e5-4299-a0f3-360774b75a65

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [X] I have followed all the guidlines mentioned in CONTRIBUTING.md.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation (if applicable).
- [X] I have tested it locally and it works fine.
- [X] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [X] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

### CODE REVIEW

**Comment by Harshdev098** [comment]
Will review and merge till night

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
Remove the script from faculty.html

**Comment by T-Rahul-prabhu-38** [comment]
@Harshdev098 done.

**Comment by T-Rahul-prabhu-38** [comment]
@Harshdev098 i have made the changes.

**Pull request merged**
