### PR TITLE
Solved Links not working in the readme.md

### LINKED ISSUE #148: Links not working in the readme.md
Some of the links in the Table of Content is not working in the Readme.md

### PR DESCRIPTION
**Pull request by ygowthamr**
### Summary  
This pull request addresses the issue of broken links in the `README.md` file. All non-functional links have been identified and corrected to ensure smooth navigation and better user experience.

### Changes Made  
- Fixed broken links in the `README.md` file.  
- Verified all updated links to ensure they point to the correct resources.  

### Impact  
- Improved accessibility to documentation and external references.  
- Enhanced user experience by eliminating dead links.  

### Testing  
- Manually checked each link to confirm they are working correctly.

Fixes #148

@Harshdev098 
Pls give me level2,gssoc-extd,hacktoberfest,etc.

### CODE REVIEW

**Comment by ygowthamr** [comment]
@Harshdev098 
Pls merge my pr

**Comment by ygowthamr** [comment]
@Harshdev098 
Yes, I have tested the links are working

**Comment by alo7lika** [comment]
@MastanSayyad , @RadhikaMalpani1702 isn't this should be level 1?

**Comment by MastanSayyad** [comment]
Hi @alo7lika Dont worry, you are not the only one who is being reviewed, whole leaderboard is. For him the review is under process your review was assign to her, after this Contributors review we will reduce it too.

**Comment by MastanSayyad** [comment]
@Harshdev098 you didn't add me as a collaborator yet, kindly reduce labels from level 2 to level 1 and add me.

**Pull request merged**
