### PR TITLE
✨the multi language support has been added to all the pages.✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
@Harshdev098 can you please review this , thank you
#152 solved.

https://github.com/user-attachments/assets/ff24408b-e62b-4058-a234-eb3a4480ea17

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@harish08102004 can you reveiw this PR.

**Comment by harish08102004** [comment]
Yeah I can do that.
Can I do that before Tomorrow EOD?

**Comment by T-Rahul-prabhu-38** [comment]
sure np

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
increase the size of gtranslate_wrapper on every page somthing liike thenavbar fontsize, the visibility is very low

image

image

**Comment by T-Rahul-prabhu-38** [comment]
ok ill make it appear as a button.

**Comment by T-Rahul-prabhu-38** [comment]
@Harshdev098 the issue is fixed.
Screenshot 2024-10-17 at 11 59 10 PM

**Comment by T-Rahul-prabhu-38** [comment]
@Harshdev098 can you review this

**Comment by Harshdev098** [comment]
You have changed the layout position of the navbar elements I just told you to increase the font-size of it don't add color or anything else

image

**Comment by T-Rahul-prabhu-38** [comment]
ohh , ill fix that

**Comment by T-Rahul-prabhu-38** [comment]
@Harshdev098 i have fixed it.
Screenshot 2024-10-18 at 9 53 15 AM

**Comment by T-Rahul-prabhu-38** [comment]
@Harshdev098 can you please review this , thank you.

**Pull request merged**
