### PR TITLE
Added Dark Toggle to the website

### PR DESCRIPTION
**Pull request by Ankitha2130**
Completed #49

### CODE REVIEW

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
While toggling the dark mode, the font color should also change(its not visible till now)
also if you can add a dark mode toggle in the  user profile it should be great. The btn is already there but it does not handle toggle event

Screenshot from 2024-10-07 16-57-57
Screenshot from 2024-10-07 17-00-06
Screenshot from 2024-10-07 16-59-33
Screenshot from 2024-10-07 17-00-06

**Comment by Ankitha2130** [comment]
I made the changes. While toggling the dark mode, the font color is also changing. And in dashboard.html i made light and dark mode button working changes. Please do review once.

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
Every thing is good now, but their is still a problem in the profile page of the students
the field parameters background should be set to dim light and font-color of the content should be visible on toggling dark mode 

Screenshot from 2024-10-08 16-27-45

**Comment by Ankitha2130** [comment]
can you please review it once

**Pull request merged**
