### PR TITLE
Enhancing the footer and removing irrelevant items and adding meaningful context, adding a "Rights" section

### LINKED ISSUE #348: Enhancing the footer and removing irrelevant items and adding meaningful context, adding a "Rights" section
Enhancing the footer and removing irrelevant items and meaningful context, and adding  a rights section to the footer.
Screenshot 2024-10-31 085421

### PR DESCRIPTION
**Pull request by shriyadindi**
## 📋 Description
Enhancing the footer and removing irrelevant items and adding meaningful context, adding a "Rights" section.

issue no.: #348 

## ✅ Checklist

https://github.com/user-attachments/assets/106da435-0ac1-4086-8398-bf45b1125955

Before submitting the PR, please make sure you have completed the following:

- [x] I have followed all the guidlines mentioned in CONTRIBUTING.md.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] Bug fix (non-breaking change which fixes an issue) 🐛
- [x] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

- Fixes #348

### CODE REVIEW

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
The previous one is looking better, what you can do just leave the other section in the footer as usual other than follow us section and copyright is good

don't change these section

Screenshot from 2024-11-01 12-35-51

**Comment by shriyadindi** [comment]
@Harshdev098 I've removed the online shop as it seems to be irrelevant and replaced it with resources, should I keep this change?

**Comment by Harshdev098** [comment]
The content you have removed is ok just keep the layout style

**Comment by shriyadindi** [comment]
@Harshdev098 I've made the changes and opened a new PR for it, kindly review it.
https://github.com/Harshdev098/Research-Nexas/pull/361

**Comment by shriyadindi** [comment]
@Harshdev098 kindly Assign the labels

**Comment by MastanSayyad** [comment]
@Harshdev098 Add labels to this PR

**Pull request merged**
