### PR TITLE
Updated CSS and made it more interactive

### PR DESCRIPTION
**Pull request by Anu27n**

### CODE REVIEW

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
The faculty page UI has to be modified 
Screenshot from 2024-10-07 01-42-19

**Comment by Anu27n** [comment]
Like what changes do u want in css only u want right?

**Comment by Harshdev098** [comment]
Actually it's not looking good

**Comment by Anu27n** [comment]
only faculty page?

**Comment by Harshdev098** [comment]
Yes

**Comment by Anu27n** [comment]
I have opened new pull request to improve UI

**Comment by Harshdev098** [comment]
Then delete the updated faculty file here because the changes persist here, I can't merge it with that

**Comment by Anu27n** [comment]
I am closing this pull request.

**Comment by Anu27n** [comment]
Deleted the file.

**Comment by Harshdev098** [comment]
@Anu27n Made another PR for these changes i have reverted it because it deleted the original file from main branch

**Pull request merged**
