### PR TITLE
Add a pop up dialog box for Polls/Survey done ! #322 🌟🌟🌟

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature - #322
Add a pop up dialog box for Polls/Survey done properly - 

https://github.com/user-attachments/assets/5dfdca33-1776-40cb-8fde-697600aa9152

Screenshot 2024-10-30 012451
Screenshot 2024-10-30 012505

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] I have followed all the guidlines mentioned in CONTRIBUTING.md.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [x] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@Harshdev098 Sir done #322

Screenshot 2024-10-30 014944



Sir I have added this feature correctly (if you vote once, you won't see it again after reload..), please merge my PR with Level 3, still this task #290 is pending and no more time, because today is the end..

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
Revert the changes you have done in the script.js for pop up of poll, will do it later

**Comment by Subhajit-2023-44** [comment]
> Revert the changes you have done in the script.js for pop up of poll, will do it later

@Harshdev098 sir u said to keep all files separately so i did it, 

then what do i do now ?? please tell

**Comment by Subhajit-2023-44** [comment]
sir please merge my PR

**Comment by Harshdev098** [comment]
Just comment the code for pop up of the dialog box for the poll and commit it I will merge your pr @Subhajit-2023-44

**Comment by Subhajit-2023-44** [comment]
> Just comment the code for pop up of the dialog box for the poll and commit it I will merge your pr @Subhajit-2023-44

sir i didn't understand 😭 please tell

**Comment by Harshdev098** [comment]
Remove the lines of code in the script file that enable the popup of poll dialog box and commit those changes @Subhajit-2023-44

**Comment by Subhajit-2023-44** [comment]
> Remove the lines of code in the script file that enable the popup of poll dialog box and commit those changes @Subhajit-2023-44

@Harshdev098 sir can i add these script file code in html or remove ??

**Comment by Harshdev098** [comment]
Remove the script for pop up of poll dialog box

**Comment by Subhajit-2023-44** [comment]
> Remove the script for pop up of poll dialog box

Okay sir

**Comment by Subhajit-2023-44** [comment]
> Remove the script for pop up of poll dialog box

done

**Pull request closed without merging**
