### PR TITLE
fix: alignment of paragraph/images in the cards

### LINKED ISSUE #283: Fixing alignment of paragraph/images in the cards
Fixing alignment of paragraph/images in top services for smaller screen size

image

### PR DESCRIPTION
**Pull request by trinetra110**
## 📋 Description

Fixed the alignment of paragraphs/images in the cards and formatted the file structure of home page.

## 🔨 Changes Made

- Changed the box's width from 22vw to 18em and height from 41vh to 20em in "style.css"
- Formatted the file structure

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] I have followed all the guidelines mentioned in CONTRIBUTING.md.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

- Fixes #283 

## 📸 Screenshots (if applicable)

- Desktop

Screenshot 2024-10-24 172137

- Tab

Screenshot 2024-10-24 172159

- Phone

Screenshot 2024-10-24 172248

---

*Thank you for contributing to Research Nexus! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by trinetra110** [comment]
@Harshdev098 I have made the required changes. Please review it and add the 'hacktoberfest', 'hacktoberfest-accepted', 'gssoc-ext' and 'level3' tags.

**Comment by Harshdev098** [comment]
branch has some conflicts resolve them!

**Comment by trinetra110** [comment]
@Harshdev098 Conflicts resolved, please check.

**Comment by trinetra110** [comment]
@Harshdev098 Please add the 'hacktoberfest', 'hacktoberfest-accepted', 'gssoc-ext' and 'level3' tags.

**Comment by trinetra110** [comment]
> @Harshdev098 Please add the 'hacktoberfest', 'hacktoberfest-accepted', 'gssoc-ext' and 'level3' tags.

@Harshdev098 ??

**Pull request merged**
