### PR TITLE
ADDING Future Enhancements/Roadmap SECTION ON README

### LINKED ISSUE #131: ADDING Future Enhancements/Roadmap SECTION ON README
**Describe the Bug**
The "Future Enhancements/Roadmap" section is currently missing or lacks detailed information about the planned features or improvements for future versions of the application. This absence can lead to confusion among users and contributors regarding upcoming functionalities and the overall direction of the project.

**To Reproduce**

Go to the README.md file of the Research Nexas repository.
Look for a section labeled Future Enhancements or Roadmap.
Notice that there is no information provided or the section is entirely absent.

**Expected Behavior**
I expected to find a clearly outlined Future Enhancements/Roadmap section detailing planned features, improvements, and timelines for the application. This would help users understand what to anticipate and how they can contribute to these upcoming features.

**Screenshots**

(Insert a screenshot of the README file without the roadmap section.)

**Additional Context**
Providing a roadmap is essential for guiding development and enhancing collaboration within the project. A well-defined roadmap can help attract potential contributors and keep current users informed about the future direction of the application. Without this section, users may feel unsure about the project's long-term vision and how they can participate in its development.
)
ASSIGN ME THIS WORK UNDER GSSOC EXT 24 AND HACKTOBERFEST (ALSO ADD LABELS)

### PR DESCRIPTION
**Pull request by alo7lika**
## 📋 Description

This PR adds a **Future Enhancements / Roadmap** section to the `README.md`. The purpose of this section is to provide users with a clear and detailed outline of upcoming features and enhancements to the Research Nexus platform. It aims to give the community and contributors a better understanding of the project's direction.

## 🔨 Changes Made

- Added a **Future Enhancements / Roadmap** section to the `README.md`.
- Used a table format with emojis to make it visually appealing and easy to follow.
- Listed planned milestones from Q4 2024 to Q1 2026, with descriptions of new features and improvements.

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] I have followed all the guidelines mentioned in CONTRIBUTING.md.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [x] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [x] Documentation update 📚

- Fixes #131 
## 📸 Screenshots (if applicable)
Screenshot 2024-10-15 102932

---

*Thank you for contributing to Research Nexas! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by alo7lika** [comment]
@Harshdev098  the task has been completed. Kindly Review it!
Thank you!

**Comment by Harshdev098** [comment]
@alo7lika Thank you for adding this section. Will add more points to it

**Review by RadhikaMalpani1702 — COMMENTED** [review]
@mastansayyad Can you review this PR?

**Review by MastanSayyad — COMMENTED** [review]
level 2 for a readme table should not have level 2, it is good for documenting but higher levels are for intermediate and complex logics 

Update it to level 1

image

**Pull request merged**
