### PR TITLE
Added  hamburger

### PR DESCRIPTION
**Pull request by pallaviii21**
added a hamburger which includes existing nav bar options enabling responsiveness.

https://github.com/user-attachments/assets/c15864fb-ca22-4a9b-b3a1-b2550a9cefbc

### CODE REVIEW

**Comment by prvn-kumar01** [comment]
Hey @Harshdev098 
merge this branch
i have completed my work

**Comment by pallaviii21** [comment]
Hey @Harshdev098 merge this branch 
I have completed my work

**Comment by pallaviii21** [comment]
Why are you ignoring my comment @Harshdev098

**Comment by Harshdev098** [comment]
The same problem is with this PR, its adding the .vscode folder and don't change the format of the project directory you have duplicated the index and style code in gssoc folder

image

**Comment by prvn-kumar01** [comment]
I'll fix it

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@Harshdev098 sir told me to help you regarding this issue

@pallaviii21 1. open the pull requests of the issue you are working on
2. go for the files changed 
3. there it shows the files in the opions you delete the json file 
4. commit changes

**Comment by pallaviii21** [comment]
Should I delete the json file?

**Comment by Harshdev098** [comment]
Yes

**Comment by pallaviii21** [comment]
Now Check it??

**Comment by Harshdev098** [comment]
also delete gssoc folder its seems duplicate file of the index.html and style.css

**Comment by prvn-kumar01** [comment]
It has researchNexas.html and researchNexas.css

**Comment by pallaviii21** [comment]
It has researchNexas.html and researchNexas.css

**Comment by pallaviii21** [comment]
Should I delete both

**Comment by Harshdev098** [comment]
Yes

**Comment by pallaviii21** [comment]
I have deleted both files 
Now check it

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
The hamburger is shown at very minimum screen size increase it to something like 770px, the navbar structure is not maintained at 770px screen size. Also make the font size of the content in the hamburger(about,home....) 

Screenshot from 2024-10-09 10-26-04

**Comment by pallaviii21** [comment]
@Harshdev098 sir actually the top nav bar was collapsing near 650px but I can alter it if you want so and also the font size.

**Comment by pallaviii21** [comment]
@Harshdev098 sir I have made the changes. Please check

**Comment by Harshdev098** [comment]
there has been no commits in between @pallaviii21 . The issue persists!

Screenshot from 2024-10-09 18-23-04

**Comment by pallaviii21** [comment]
@Harshdev098 Sir please check again, I have synced the changes.
image
 But I have no idea about that home button which on your side is getting below the navbar, because I am not facing that issue on my side

**Comment by Harshdev098** [comment]
Its seems the page is not responsive 

image

image

**Comment by pallaviii21** [comment]
https://github.com/user-attachments/assets/9fa3d4db-5ba2-45cf-a7ff-a944c8b2d7f8

But @Harshdev098 sir I'm not facing this problem here, plus I haven't changed any styling of top navigation bar. I reallly don't have any idea about that.

**Comment by pallaviii21** [comment]
@Harshdev098 sir, please consider my work. I have completed

**Comment by Harshdev098** [comment]
Sorry, but I can't merge this PR, The issue still persists 
The page is not responsive

**Pull request closed without merging**
