### PR TITLE
fix: adjusted the size of dark-theme icon changed some icons

### LINKED ISSUE #195: [BUG]: Size of the dark-theme icon is huge in Stakeholder's main page
**Describe the bug**
Size of the dark-theme icon is huge in Stakeholder's main page

**To Reproduce**
1. Go to Login page of Stakeholder
2. Login with your details and you will be redirected to the main page of Stakeholder

**Expected behavior**
Appropriate size of the dark-theme icon in the top right corner of the page like other pages

**Screenshots**

- Desktop/laptop
Screenshot 2024-10-18 125659

- Phone
Screenshot 2024-10-18 125903

**Additional context**
None

@Harshdev098 Please assign this issue to me and add 'hacktoberfest', 'gssoc-ext' and a 'level' labels to it.

### PR DESCRIPTION
**Pull request by trinetra110**
## 📋 Description

Adjusted the size of the dark-theme icon in Stakeholder's main page, changed some icons, keeping it responsive across all devices, navbar color changed to black, and fixed the position of the user icon.

## 🔨 Changes Made

- Changed size of icon in 'stk_mainpage.html' keeping it responsive
- Changed some icons in 'stk_mainpage.js' for better visibility
- Changed the color of navbar to black
- Fixed the position of user icon

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] I have followed all the guidelines mentioned in CONTRIBUTING.md.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

- Fixes #195 

### User icon position before changes

Screenshot 2024-10-18 201852

## After changes
- Desktop/laptop

Screenshot 2024-10-18 201145

- Phone

Screenshot 2024-10-18 201610

- Tab

Screenshot 2024-10-18 201553

---

*Thank you for contributing to Research Nexus! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by trinetra110** [comment]
@Harshdev098 I have made the required changes. Please review it and add the 'hacktoberfest', 'hacktoberfest-accepted', 'gssoc-ext' and 'level2' tags.

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
Make the navbar background color balck so that the logo should be visible

**Comment by trinetra110** [comment]
Ok

**Comment by trinetra110** [comment]
@Harshdev098 Please review the changes.

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
decrease the height of the navbar from 6rem to 5rem
Also the dark mode is not working

**Comment by trinetra110** [comment]
> decrease the height of the navbar from 6rem to 5rem
> Also the dark mode is not working

@Harshdev098 Ok I will change the height of the navbar but the dark mode is not working from the starting and this issue is not related to it, so I prefer to open a new issue for it.

**Comment by Harshdev098** [comment]
Yah sure

**Pull request merged**
