### PR TITLE
Improved Password validation and sequirity by improvig criterias for … …valid password and adding rate limitation

### LINKED ISSUE #31: Improving Password Validation during login and signup of Users
While going through the login and signup routes I noticed that the password validation can be done better  

An optimal password validation system needs to be done to ensure better input validation while signup and login

### PR DESCRIPTION
**Pull request by RishiVT2004**
Fixed #31 

Improved passworde validation by adding the following condition for a valid password 
A valid password mush be -: 
1. of min length 7 
2. contain 1 uppercase and 1 lowercase letter 
3. contain 1 number 
4. contain 1 special digit like [@,$,!,etc]

Also added rate limiting to limit no. of attempts in the api

### CODE REVIEW

**Comment by RishiVT2004** [comment]
@Harshdev098 please review this

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
Its running well, but the client should handle this response from the server to show the conditions user have to take care off. Add a handler for this response status in the login client side.
Also please follow the contributing.md guidelines add `fixes<issue_number> ` in PR description referencing the issue you are solving, 
I have added level3 label

**Comment by RishiVT2004** [comment]
ok , sorry i will add it

**Comment by RishiVT2004** [comment]
@Harshdev098 i am sorry but in the request you have asked me to make i have to implement client-side logic using React/JS for the login and signup functions, actually i am experienced in frontend work , so it is better if i do not solve this as i don't want to mess up the project , respectfully it will be better if someone else solves this 

If there is any other way i can help in backend (nodejs/mongodb/nosql) i am willing to help

**Comment by Harshdev098** [comment]
Okay, no problem will handle that

**Comment by RishiVT2004** [comment]
thank you very much for your understanding @Harshdev098 , please merge this pr if you think there is no more changes to be made

**Pull request merged**
