### PR TITLE
Implement Newsletter Saving Functionality

### LINKED ISSUE #385: Feature : Save Newsletter Email to Database
### Describe the feature

**Description**:  
Add a feature to save users' newsletter email addresses to the database for future communications and email campaigns.

**Requirements**:
- Create an endpoint to accept and validate email submissions.
- Store valid email addresses in the database with a timestamp.
- Handle duplicate entries by checking for existing emails before adding new ones.

**Expected Outcome**:  
A database table to store newsletter emails, along with a backend endpoint to capture and save these emails.

**Additional Notes**:
This feature will help in building a mailing list for newsletters, promotional content, and updates.

### Add ScreenShots

- image

@Harshdev098 Pls assign me this issue, give me level, label.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ygowthamr**
### PR: Implement Newsletter Saving Functionality

Fix #385

1. Implements saving user email addresses to the database for newsletter subscriptions.
2. Ensures only valid email formats are accepted before saving.
3. Includes robust error handling for database operations.
4. Provides clear feedback to users regarding their subscription status.
5. Aims to improve user engagement by facilitating newsletter subscriptions through the application.

**Note:**
 - **Dont forget to create database table as shown below**
 - image

@Harshdev098 
Pls assign me this PR, give me level, lable.

### CODE REVIEW

**Comment by ygowthamr** [comment]
@Harshdev098 
Pls review and merge my PR.

**Comment by Harshdev098** [comment]
@ygowthamr If you are making an other db table just give the queries in the Readme.md 
Edit Readme so that everyone can find these queries

**Comment by ygowthamr** [comment]
@Harshdev098 Updated pls check and merge my PR.

**Comment by ygowthamr** [comment]
@Harshdev098 
Pls review and merge my PR.

**Pull request merged**
