### PR TITLE
Refactor/mysql connection setup

### PR DESCRIPTION
**Pull request by harish08102004**
Fixed issue:
#59 

This PR refactors the code by moving the MySQL connection pool setup into a separate config/mysql_connection.js file. Instead of duplicating the pool creation across multiple files, we now centralize the database connection logic. This improves maintainability and consistency across the project.

### CODE REVIEW

**Comment by harish08102004** [comment]
Hey @Harshdev098 Please add labels, check and merge it.

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
You have not configured the mysql connection in the stakeholder directory, those files are still using seperate mysql connections

**Comment by harish08102004** [comment]
Oops ,my bad I didn't see it.
give me a min I will make those changes also.

**Comment by harish08102004** [comment]
hey @Harshdev098 updated the stakeholder directory also.

**Pull request merged**
