### PR TITLE
Added color to the follow us icons on hovering

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
Added color to the follow us icons on hovering and on clicking to make attractive follow us section and also arranged 2 icons on each row to look better

Uploading researchnexas2.mp4…

### CODE REVIEW

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
Don't add styling code in the index.html, it should be in the style.css file

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Ok

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
made changes please have a look at them

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir please have a loot at pull request -removed json updation

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
its not done! the vs code folder is still there

image

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
should i delete it

**Review by KapuluruBhuvaneswariVspdbct — COMMENTED** [review]
its done

**Comment by Harshdev098** [comment]
Could please help a contributor in the pr #60 to solve this same issue

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir can u please tell me the score

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
> Could please help a contributor in the pr #60 to solve this same issue

yes  sir definitely

**Comment by Harshdev098** [comment]
You can check it on GSSoC leaderboard page

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
for this specific project sir

**Pull request merged**
