### PR TITLE
Password_Minimum_Requirement_For_Signup

### PR DESCRIPTION
**Pull request by smog-root**
**Fixes** #113 

**Password Requirements:**

- At least 8 characters long.
- At least 1 uppercase letter (A-Z).
- At least 1 lowercase letter (a-z).
- At least 1 number (0-9).
- At least 1 special character (e.g., !@#$%^&*()).

when a user tries to register, they will receive immediate feedback if their password does not meet these criteria. Let me know if you need any further changes or additional features!

**signup.html**

signup.html

Note:- Add all labels added to issue #113 to this PR. So that GSSoC team can easily recognize the commit! also add hacktoberfest-accepted label!

### CODE REVIEW

**Review by Ajay-singh1 — APPROVED** [review]
LGTM!

**Comment by smog-root** [comment]
Add gssoc-ext with level3 and hacktoberfest-accepted labels!

**Comment by Harshdev098** [comment]
@smog-root Is this feature only applicable only if user clicks on the register or it will check the password while entering in the fields

**Comment by smog-root** [comment]
It popups only if the user clicks on the registration button!

**Comment by Harshdev098** [comment]
This feature is already implemented for student authentication

**Comment by smog-root** [comment]
But not for signup!!!

**Comment by smog-root** [comment]
Someone needs to add it right!!

**Comment by smog-root** [comment]
When you will merge it?? #115 and #114

**Comment by Harshdev098** [comment]
Its already there for signup of student also but not for stakeholders

image

**Comment by smog-root** [comment]
ok then add merge #115 .

**Pull request closed without merging**
