### PR TITLE
Refactor display function for improved error handling and code clarity

### PR DESCRIPTION
**Pull request by RishiVT2004**
Fixes issue no #126 
**Changes Made -:** 

- Enhanced token validation and user information checks.
- Promisified the database query execution for cleaner async/await syntax.
- Added structured response format for better API consistency.
- Implemented error handling for cases where the user is not found in the database.

### CODE REVIEW

**Comment by RishiVT2004** [comment]
@Harshdev098 pease review this PR

**Comment by Harshdev098** [comment]
Its not that much effective, there are many changes to be done in this

**Review by Harshdev098 — COMMENTED** [review]
- You have not added the correct modules 
- Don't change the naming of the token variables, we have used the same in every files for better understanding
- Also use single line sql queries

**Comment by RishiVT2004** [comment]
@Harshdev098 may I know which modules are to be added

**Comment by Harshdev098** [comment]
You have removed decodedaccesstoken, db, MySQL that are required in the file

**Pull request closed without merging**
