### PR TITLE
Add PWA (Progressive Web App) done ! #396

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add/Enable PWA (Progressive Web App) done ! #396 

https://github.com/user-attachments/assets/4f9cba61-e2bd-408d-9e87-0137211561f9

Screenshot 2024-11-06 230210

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] I have followed all the guidlines mentioned in CONTRIBUTING.md.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [x] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

*Thank you for contributing to Research Nexus! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@Harshdev098 done #396 

please merge my PR with level 3 and gssoc-ext label

**Comment by Harshdev098** [comment]
@Subhajit-2023-44 Its not working in localhost

image

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 Its not working in localhost

@Harshdev098 But sir it is working properly on my device..

Screenshot 2024-11-07 145251
Screenshot 2024-11-07 145315

**Comment by Subhajit-2023-44** [comment]
image

**Comment by Harshdev098** [comment]
> image
> 

Is this on localhost or live server? @Subhajit-2023-44

**Comment by Subhajit-2023-44** [comment]
> Is this on localhost or live server? @Subhajit-2023-44

@Harshdev098 live server

**Comment by Harshdev098** [comment]
Yah but it's not working on localhost:3000

**Comment by Subhajit-2023-44** [comment]
> Yah but it's not working on localhost:3000

@Harshdev098 but if it not working in localhost, you can merge my pr and then check using website link, I am sure it working because i already did it in 3-4 website..

**Comment by Subhajit-2023-44** [comment]
> > Yah but it's not working on localhost:3000
> 
> @Harshdev098 but if it not working in localhost, you can merge my pr and then check using website link, I am sure it working because i already did it in 3-4 website..

After merge -

Screenshot 2024-11-07 151007
Screenshot 2024-11-07 151036
Screenshot 2024-11-07 151107

**Comment by Harshdev098** [comment]
the active property should be null 

image

**Comment by Subhajit-2023-44** [comment]
> the active property should be null
> 
> image

@Harshdev098 sorry sir i didn't understand what you said, Sir can you please tell me now what can i do..

**Comment by Harshdev098** [comment]
its not populating on live server 
Its giving service errors
```
Registration failed with TypeError: ServiceWorker script at http://127.0.0.1:5500/script/sw.js for scope http://127.0.0.1:5500/ encountered an error during installation. [<anonymous code>:1:145535](chrome://devtools/content/webconsole/%3Canonymous%20code%3E)
    overrideMethod <anonymous code>:1
```

**Comment by Subhajit-2023-44** [comment]
> its not populating on live server Its giving service errors
> 
> ```
> Registration failed with TypeError: ServiceWorker script at http://127.0.0.1:5500/script/sw.js for scope http://127.0.0.1:5500/ encountered an error during installation. [<anonymous code>:1:145535](chrome://devtools/content/webconsole/%3Canonymous%20code%3E)
>     overrideMethod <anonymous code>:1
> ```

@Harshdev098 ok sir i will try to solve this issue, please wait i will give new pr within 1 hours

**Comment by Subhajit-2023-44** [comment]
@Harshdev098 sir done, Now it is showing no error and working..

Please check & merge my PR 

Thank You

**Pull request closed without merging**
