### PR TITLE
Solved ''View the File link'' is not working for the stakeholder while allotment and approval of paper issue

### PR DESCRIPTION
**Pull request by ygowthamr**
**Solved the below issue: **
View the File link is not working for the stakeholder while allotment and approval of paper

### CODE REVIEW

**Comment by ygowthamr** [comment]
Solved View the File link is not working for the stakeholder while allotment and approval of paper

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
The link is still not working 

Screenshot from 2024-10-11 09-37-35


Also the `View the file` is replicating itself on very clinks, just how many time i open any of the research paper it will be replicated

Screenshot from 2024-10-11 09-38-01

**Comment by ygowthamr** [comment]
@Harshdev098 
I will solve the view file replicated issue asap.
For the older files in the db the path is different once reupload the file and try to open the newly uploaded file it will work.

**Comment by ygowthamr** [comment]
@Harshdev098 
I have updated the view file duplicate issue pls check and merge,
Also i want the girlscript and hacktober tags in pull request

**Comment by Harshdev098** [comment]
Can you tell what is the fault because of what the link is not working

**Comment by ygowthamr** [comment]
@Harshdev098 
Pls check now i have changed all the points you have said i think now it should work

**Comment by Harshdev098** [comment]
can you specify the changes or give a overview of what you have changed to fix the link its very exhausting to see the changes in between the changes of inverted commas and colon

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
The replication is fixed but the link is still not working 

Screenshot from 2024-10-11 12-27-10

**Comment by ygowthamr** [comment]
@Harshdev098 
The following changes i have done: 
1 . In stk_approval.js file from line no 70 to 78 i have added the below code
`
                        if (result != 0) {
                            const filepath = result[0].filepath
                            const filename = result[0].filename
                            const name = result[0].name
                            const email = result[0].email
                            const col_name = result[0].col_name
                            const sno = result[0].sno;
                            res.json({ filepath, filename, name, email, col_name, sno })
                        }
`
2 . In approval.js file from line no 94 to 112 i have updated the below code
`
  if (response.ok) {
    const details = await response.json();
    let a = path.querySelector("a");
    if (!a) {
      a = document.createElement("a");
      a.target = "_blank";
      path.appendChild(a);
    }
    a.href = `/uploads/${details.filename}`;
    a.textContent = "View the file";
    name.textContent = details.name;
    email.textContent = details.email;
    sno.textContent = details.sno;
    col_name.textContent = details.col_name;
    const btn = document.getElementById("approve");
    btn.onclick = () => {
      approval(details.sno);
    };
  }
`
3 . In paper_allotment.js file from line no 87 to 106 i have updated the below code
`
  if (response.ok) {
    const details = await response.json();
    let a = path.querySelector("a");
    if (!a) {
      a = document.createElement("a");
      a.target = "_blank";
      path.appendChild(a);
    }
    a.href = `/uploads/${details.filename}`;
    a.textContent = "View the file";

    name.textContent = details.name;
    email.textContent = details.email;
    sno.textContent = details.sno;
    col_name.textContent = details.col_name;
    const btn = document.getElementById("approve");
    btn.onclick = () => {
      fac_allotment(details.sno);
    };
  }
`

I have forgot to add parm in the response json in stk_approval file pls check now it will work fine.

**Comment by ygowthamr** [comment]
**Pls add me labels for hacktoberfest and gssoc-extd**

**Review by Harshdev098 — COMMENTED** [review]
Yah its fixed!

**Pull request merged**
