### PR TITLE
Add git contributors page

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #155 
Screenshot 2024-10-17 at 2 46 55 AM

### CODE REVIEW

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
Don't add the git Contributors link in the index.html just discard these changes in the index.html file, I will add it somewhere. Also edit the github link in the `gitContributors.html` file its refering to your forked repo

**Comment by shubhagarwal1** [comment]
> Don't add the git Contributors link in the index.html just discard these changes in the index.html file, I will add it somewhere. Also edit the github link in the `gitContributors.html` file its refering to your forked repo

understood making changes

**Comment by shubhagarwal1** [comment]
@Harshdev098 
done the changes 
reverted the index file 
added correct git link

**Comment by Harshdev098** [comment]
@shubhagarwal1 You have closed this, are you going to create new pr for it

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 You have closed this, are you going to create new pr for it

@Harshdev098 mistakenly i did that, reopened the PR

**Comment by Harshdev098** [comment]
@shubhagarwal1 The changes are not visible its showing same link for github(your forked repository)

**Comment by shubhagarwal1** [comment]
@Harshdev098 t

**Comment by shubhagarwal1** [comment]
@Harshdev098 
Screenshot 2024-10-18 at 12 45 01 AM

**Comment by NEGRAH-S** [comment]
@MastanSayyad , These changes shall be categorised under level 2 hence changing .

**Pull request merged**
