### PR TITLE
Added: Data to Top services Section

### LINKED ISSUE #91: Adding Data: To Top Services Section
I would like to to add  icons along with data in Top Services section

Kindly please assign this task for me under gssoc-extd, hacktoberfest-accepted, and level2

Here is sample 👇
image

### PR DESCRIPTION
**Pull request by siri-chandana-macha**
Issue Fixed #91 

## 🔨 Changes Made

Modified the Top services section  and added icons

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] I have followed all the guidlines mentioned in CONTRIBUTING.md.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

- Fixes #

## 📸 Screenshots (if applicable)
Screenshot 2024-10-12 211043

Screenshot 2024-10-12 211102

Screenshot 2024-10-12 211117

### CODE REVIEW

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
Remove these points in this- 
1. Connect with peers
2. Reedem badges

Also edit the Explore Project to Explore Papers

**Comment by siri-chandana-macha** [comment]
Ok I will change it to explore papers..should I replace points in connect
with peers and Reedem badges ?

**Comment by Harshdev098** [comment]
Yes

**Comment by siri-chandana-macha** [comment]
Could you please review my changes and let me know if any further modifications are needed?
<br>
Screenshot 2024-10-13 153519
Screenshot 2024-10-13 153533

**Comment by Harshdev098** [comment]
> Remove these points in this-
> 
>     1. Connect with peers
> 
>     2. Reedem badges
> 
> 
> Also edit the Explore Project to Explore Papers

@siri-chandana-macha What you have removed here, all the thing is already there, there has been no changes in it also the changes are not shown in file changed section

image

**Comment by siri-chandana-macha** [comment]
I modified points in connect with peers and reedem badges and made a commit
modifying changes yesterday

**Comment by Harshdev098** [comment]
Also change the explore project to explore paper it's not showing that changes

**Comment by siri-chandana-macha** [comment]
Ok .You wanted me to remove entire section of connect with peers and reedem
badges I thought only points

**Comment by siri-chandana-macha** [comment]
Ok

**Comment by Harshdev098** [comment]
Yes

**Review by siri-chandana-macha — COMMENTED** [review]
image
I made changes please look into it and merge it

**Pull request merged**
