### PR TITLE
Enhancing the contributor Section and Structuring

### LINKED ISSUE #224: Enhancing the contributor Section and Structuring
### **Describe the Bug**
The contributor section in the README file lacks an appealing structure and does not highlight the contributors effectively. Enhancements are needed to structure the section properly, making it more organized, visually attractive, and easy to navigate.

### **To Reproduce**
1. Go to the README file on the repository.
2. Scroll down to the contributor section.
3. Observe the unstructured and cluttered appearance.

### **Expected Behavior**
The contributor section should have a clean and well-organized structure. Each contributor's profile picture should be displayed alongside their name, and the names should be clickable links that redirect to their GitHub profiles. Ideally, the section should be presented in a grid or table format for better visibility and ease of access.

### **Screenshots**
If applicable, add screenshots to show the current state of the contributor section and mockups of the desired format.

### **Additional Context**
The enhancement involves restructuring the contributor section using a table layout, showing contributor images alongside clickable GitHub profile links, and possibly adding a slideshow feature for better visualization.

### PR DESCRIPTION
**Pull request by alo7lika**
## 📋 Description

This pull request enhances the contributor section and structures it for better clarity and presentation. The goal is to improve the overall readability and visual appeal of the contributors' information.

## 🔨 Changes Made

- Enhanced the layout of the contributor section.
- Centered contributor names for improved readability.
- Reduced the table size for better alignment and presentation.

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] I have followed all the guidelines mentioned in CONTRIBUTING.md.
- [x] My code adheres to the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

Fixes #224 

## 📸 Screenshots (if applicable)

The following screenshots demonstrate the updates to the contributor section, showing the enhanced layout and centered names:

Screenshot 2024-10-20 141504

---

*Thank you for contributing to Research Nexus! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by alo7lika** [comment]
@Harshdev098  the task has been completed.

**Review by Harshdev098 — COMMENTED** [review]
Its look good but you have hardcoded the profile of contributors, what if a new contributor enters with many contributions

**Comment by alo7lika** [comment]
> It looks good but you have hard-coded the profile of contributors, what if a new contributor enters with many contributions

I appreciate your feedback regarding the hardcoded contributor profiles! While it may seem limiting to use hardcoded profiles, I chose this approach for several reasons. First, it keeps the README structure simple and allows for quick recognition of key contributors, making it easier for users to acknowledge their efforts without the overhead of implementing a dynamic system. Second, hard coding ensures consistency in formatting and presentation, which can sometimes be lost with dynamic solutions. Currently, our project has a small group of core contributors, so manually managing this section allows us to highlight their contributions prominently as we build our community. Lastly, I’m open to revisiting this approach in the future as we grow and welcome more contributors, allowing us to adapt to the project's evolving needs. Thank you for your understanding!

**Comment by alo7lika** [comment]
> > > It looks good but you have hard-coded the profile of contributors, what if a new contributor enters with many contributions
> > 
> > 
> > I appreciate your feedback regarding the hardcoded contributor profiles! While it may seem limiting to use hardcoded profiles, I chose this approach for several reasons. First, it keeps the README structure simple and allows for quick recognition of key contributors, making it easier for users to acknowledge their efforts without the overhead of implementing a dynamic system. Second, hard coding ensures consistency in formatting and presentation, which can sometimes be lost with dynamic solutions. Currently, our project has a small group of core contributors, so manually managing this section allows us to highlight their contributions prominently as we build our community. Lastly, I’m open to revisiting this approach in the future as we grow and welcome more contributors, allowing us to adapt to the project's evolving needs. Thank you for your understanding!
> 
> Sure I understand, and i agree that showing a minimal number of contributors in readme is good but I thought of displaying the top 10-12 contributors in the readme file
> 
> Okay for I am just merging it will thought about it

Thank you!

**Review by RadhikaMalpani1702 — COMMENTED** [review]
@sanjay-kv @mastansayyad can you review this PR?

**Review by MastanSayyad — COMMENTED** [review]
Readme should only have level 1 @Harshdev098 

image

**Pull request merged**
