### PR TITLE
fixed the Language change option

### PR DESCRIPTION
**Pull request by Sudhanshu248**
## 📋 Description

The language change option is placed in navbar which is not correct.

## 🔨 Changes Made

The Language change option should be present at the bottom of the screen. I've solved that issue.

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [ x] I have followed all the guidlines mentioned in CONTRIBUTING.md.
- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [x ] I have tested it locally and it works fine.
- [x ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨

- Fixes #

Before:
Screenshot 2024-10-18 161605

After:
Screenshot 2024-10-18 165847

*Thank you for contributing to Research Nexus! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by Sudhanshu248** [comment]
@Harshdev098 Please review my pr and also add the label of hacktoberfest'24, hacktoberfest-accepted, level-2.

**Comment by Harshdev098** [comment]
@Sudhanshu248 Hey, can you change the same on every page

**Comment by Harshdev098** [comment]
Because the language change btns position is not fixed on other pages and also its design like this on index.html @Sudhanshu248

**Comment by Harshdev098** [comment]
You can raise an issue regarding it

**Comment by Sudhanshu248** [comment]
@Harshdev098 Ok sir I will do it.

**Pull request merged**
