### PR TITLE
Alignment Adjustments for Mobile View

### LINKED ISSUE #368: Feature : Adjusting the Alignment of Homepage Components
### Issue: Adjusting the Alignment of Homepage Components

1. **Assessing Alignment**: Reviewing the layout of homepage components.
2. **Making Adjustments**: Realigning elements for consistent spacing and balance.
3. **Testing Responsiveness**: Ensuring the layout looks good on various devices.
4. **Maintaining Design Consistency**: Aligning changes with design standards.
5. **Documenting Changes**: Capturing before-and-after screenshots for reference.

@Harshdev098 
Pls assign me this issue, give me labels, level, etc.

### PR DESCRIPTION
**Pull request by ygowthamr**
### Alignment Adjustments for Mobile View

Fix #368 

- Adjusted alignment and layout for better display on mobile devices.
- Enhances readability and usability for mobile users, ensuring a more seamless experience on smaller screens.
- Used media queries to apply mobile-specific alignment and layout changes.

@Harshdev098 pls give me labels, level, assign me this PR.

### CODE REVIEW

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
There are some changes required for this issue- 

Screenshot from 2024-11-08 08-33-54

The hamburger should be visible when the screen size goes to 960px- 
Screenshot from 2024-11-08 08-35-09

The top services alignment should be in center for mobile view
image

**Comment by ygowthamr** [comment]
@Harshdev098 

> There are some changes required for this issue-

Can you send viewport your viewing?
Because i have made this reponsive.

**Comment by ygowthamr** [comment]
@Harshdev098 
Updated Pls check and merge my PR

**Comment by ygowthamr** [comment]
@Harshdev098 
Pls check and merge my PR.

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
It didn't fixed

image

image

**Comment by Harshdev098** [comment]
Each view port is on top:

image


image


image

**Comment by ygowthamr** [comment]
@Harshdev098 Pls check and merge my PR.

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
The hamburger is not fixed (960px X 963px)

image

**Comment by ygowthamr** [comment]
@Harshdev098 Once check and merge my PR.

**Pull request merged**
