### PR TITLE
Github action PR Issue checker

### LINKED ISSUE #178: Adding github action workflow for PR validation
The workflow checks consist of following steps-
- Should check for the PR Description in the pull request
- Check for the issue number, if the PR is not addressing any issue it should include `Fixes #NEW`

### PR DESCRIPTION
**Pull request by ygowthamr**
**What i have done :**
- Solved Adding github action workflow for PR validation

Fix #178

@Harshdev098 
Pls add me labels like gssoc-extd,level3,hacktoberfest.

### CODE REVIEW

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
```
name: Validate PR Description
runs-on: ubuntu-latest
```

add these lines in the code under validate-pr-description also change the filename to `PRValidator`

**Comment by ygowthamr** [comment]
@Harshdev098 
Sure

**Comment by ygowthamr** [comment]
@Harshdev098 
You forgot give me labels like gssoc-extd,hacktoberfest-accepted and level3

**Comment by aditya-bhaumik** [comment]
@sanjay-kv please review this pr

**Comment by sanjay-kv** [comment]
reduced the level to level1., because we have guidelines workflows cant be level 3, as its a repetitive process, people misuse the labels and tend to score on leaderboard. 
and kindly provide access to the repo

**Comment by ygowthamr** [comment]
@sanjay-kv 
Other top 10 member's GitHub actions are labeled as level2 and for this you have downgraded to level1.If you want to downgrade then downgrade it to level2.

**Comment by aditya-bhaumik** [comment]
@ygowthamr dont worry the top 10 members prs will also be reviewed and their contributions downgraded thanks for pointing it out

**Comment by MastanSayyad** [comment]
Hi @ygowthamr we are reviewing each contributor and for top 10 too (I know you are referring to that one contributor ) their points will also get reduce
Kindly follow the given guidelines, 

image

I suggest you to focus on quality contributions rather than following any other contributors practices

**Comment by ygowthamr** [comment]
@MastanSayyad 
I hardly did 5 Prs regarding workflows, All other prs are regarding different issues

**Comment by aditya-bhaumik** [comment]
@ygowthamr yes but we had added this rule in guidelines in beginning only that you can only get level 1 for workflow.
Onky your workflow updates are downgraded to level 1 none of the other contributions

And the rule is same for everyone 

Dont worry the other contributors will also be reviewed as we have noticed many people have got level 3 for workflow updates

**Pull request merged**
