### PR TITLE
Enhance the top services section

### PR DESCRIPTION
**Pull request by Sudhanshu248**
## 📋 Description

Enhance the top services section, by changing its design and hover effect.

## 🔨 Changes Made

Issue : Enhance the top services section #202
Issue no : #202 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [ x] I have followed all the guidlines mentioned in CONTRIBUTING.md.
- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ x] I have tested it locally and it works fine.
- [ x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨

- Fixes #

## 📸 Screenshots (if applicable)

Before:
Screenshot 2024-10-18 192428

After:
Screenshot 2024-10-18 204939

*Thank you for contributing to Research Nexus! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by Sudhanshu248** [comment]
@Harshdev098 Please review my pr and also add the label of gssoc'24, hacktoberfest'24, hacktoberfest-accepted, level-2.

**Comment by Harshdev098** [comment]
This pr have some conflicts, resolve them

**Comment by Sudhanshu248** [comment]
@Harshdev098 I've solved the conflict. 

Please review my pr and also add the label of gssoc'24, hacktoberfest'24, hacktoberfest-accepted, level-2.

**Comment by Sudhanshu248** [comment]
@Harshdev098 Sir, can you merge this this PR.

**Pull request merged**
