### PR TITLE
Add navbar on other pages

### LINKED ISSUE #255: Add navbar on other pages
Currently on some pages there is no button to come back to home. Which creates problem for user to come on home page from other pages.

Hence, I would like to add navbar on all pages. So that user can switch pages easily.

Screenshot 2024-10-20 225718

Screenshot 2024-10-20 225753

### PR DESCRIPTION
**Pull request by Sudhanshu248**
## 📋 Description

Currently on some pages there is no button to come back to home. Which creates problem for user to come on home page from other pages.

## 🔨 Changes Made

Issue: Add navbar on other pages #255
Issue no: #255 

I've added the navbar on all pages of website with functionality.

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [ x] I have followed all the guidlines mentioned in CONTRIBUTING.md.
- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] New feature (non-breaking change which adds functionality) ✨

- Fixes #255 

## 📸 Screenshots (if applicable)

Before: 

Screenshot 2024-10-20 225718

After:  (Contact us page)

Screenshot 2024-10-21 212506

Before:

Screenshot 2024-10-20 225753

After: (Registration page)

Screenshot 2024-10-21 212609

(Login Page):

Screenshot 2024-10-21 212656

*Thank you for contributing to Research Nexus! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by Sudhanshu248** [comment]
@Harshdev098 Please review my pr and also add the label of gssoc'24, gssoc-ext, hacktoberfest'24, hacktoberfest-accepted, level-3.

**Comment by Harshdev098** [comment]
there are conflicts, please resolve them

**Comment by Sudhanshu248** [comment]
@Harshdev098 Sir, I've solved the conflict.

Please review my pr and also add the label of gssoc'24, gssoc-ext, hacktoberfest'24, hacktoberfest-accepted, level-3.

**Comment by Harshdev098** [comment]
? fix these

image

**Comment by Sudhanshu248** [comment]
@Harshdev098 Sir I've added the navbar on all pages.

**Comment by Sudhanshu248** [comment]
@Harshdev098 Sir Can you please merge this PR as I've solve all the conflicts.

Please review my pr and also add the label of gssoc'24, gssoc-ext, hacktoberfest'24, hacktoberfest-accepted, level-3.

**Comment by Harshdev098** [comment]
it still not resolved the bottom padding is more likely to be seem

image

**Pull request closed without merging**
