### PR TITLE
I had modified the css properties for the website

### PR DESCRIPTION
**Pull request by Dipanita45**
Made the changes:
1. Font size
2. Background colour
3. Text align
4. Transition
5. Position
...etc

Issue no: #85 

Thank you @Harshdev098 for the opportunity 
Please review and label me 

I had modify the pull request @Harshdev098 
Thank you for the support.
Please review my pull request

### CODE REVIEW

**Review by Harshdev098 — CHANGES_REQUESTED** [review]
All the UI changes is good, don't change Landing page background color, floating circle colors and the navbar hovering border

**Comment by Dipanita45** [comment]
Please label

**Comment by Dipanita45** [comment]
Okay I will recheck and make a new pull request

**Comment by Dipanita45** [comment]
I had changed the pull request @Harshdev098  sir

**Comment by Harshdev098** [comment]
Nothing changed, even its not showing the commits after I made request change

**Comment by Dipanita45** [comment]
Sorry I have done the changes but it's not showing
Sorry for the inconveniences 😔

**Pull request closed without merging**
