### PR TITLE
feature: Add password toggle button for both the forms

### PR DESCRIPTION
**Pull request by RNAdvani**
## 🔨 Changes Made

- 
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [./ ] I have followed all the guidlines mentioned in CONTRIBUTING.md.
- [ ./] My code follows the style guidelines of this project.
- [ ./] I have performed a self-review of my own code.
- [ ./] I have commented my code, particularly in hard-to-understand areas.
- [ ./] I have made corresponding changes to the documentation (if applicable).
- [./ ] I have tested it locally and it works fine.
- [ ./] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [./ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

- Fixes 

## 📸 Screenshots (if applicable)

kindly add labels for this
---

*Thank you for contributing to Research Nexus! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by Harshdev098** [comment]
Someone is already assigned to this task, if he can't will merge it!

**Review by Harshdev098 — APPROVED** [review]

**Comment by Harshdev098** [comment]
@RNAdvani Please resolve branch conflicts, I will merge it

**Comment by RNAdvani** [comment]
@Harshdev098 yes resolving

**Comment by RNAdvani** [comment]
i would have to create another branch for this i would create this and link it here

**Pull request closed without merging**
